version: '3.4'

services:
  nodejsjwtauth:
    image: nodejsjwtauth
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
  db:
    image: mariadb:10.5.5-focal
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
  
